################ Chinese language ##################
[cn]
languageName = "中"
languageCode = "zh-cn"
contentDir = "content/cn"
weight = 1

################ English language ##################
[en]
languageName = "EN"
languageCode = "en-us"
contentDir = "content/english"
weight = 2


################ French language ##################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
