############# English navigation ##############

# main menu
[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "关于"
url = "about/"
weight = 2

# [[main]]
# name = "博客"
# url = "blog/"
# weight = 3

[[main]]
weight = 4
name = "其他"
hasChildren = true

# [[main]]
# parent = "其他"
# name = "元素"
# url = "elements/"
# weight = 1

[[main]]
parent = "其他"
name = "招聘"
url = "career/"

[[main]]
parent = "其他"
name = "定价"
url = "pricing/"

# [[main]]
# parent = "其他"
# name = "作者"
# url = "authors/"

[[main]]
parent = "其他"
name = "联系"
url = "contact/"

[[main]]
parent = "其他"
name = "Terms & Conditions"
url = "terms-conditions/"

# [[main]]
# parent = "Pages"
# name = "404"
# url = "404/"

[[footer_01]]
name = "About us"
url = "about/"
weight = 1

[[footer_01]]
name = "Contact us"
url = "contact/"
weight = 2

[[footer_01]]
name = "Pricing"
url = "pricing/"
weight = 3

# [[footer_02]]
# name = "Blog"
# url = "blog/"
# weight = 1

[[footer_02]]
name = "Career"
url = "career/"
weight = 2

[[footer_02]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 3
